language: r
cache: packages
cran: https://cloud.r-project.org
env:
  global:
    - CRAN_REPO=https://cloud.r-project.org
jobs:
  include:
  - os: linux
    dist: xenial
    r: oldrel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - hunspell-en-ca
          - libgdal1-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
    services:
      - xvfb
    r_binary_packages:
      - BH
      - dplyr
      - git2r
      - igraph
      - raster
      - RSQlite
    before_script:
      - Rscript -e 'install.packages("devtools", type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/map@development", dependencies = TRUE)'
      - Rscript -e 'devtools::install_github("PredictiveEcology/pemisc@development", dependencies = TRUE)'
    before_install:
      - Rscript -e 'install.packages(c("ggplot2", "quickPlot", "reproducible", "SpaDES.core"), type = "source")'
  - os: linux
    dist: xenial
    r: release
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - hunspell-en-ca
          - libgdal1-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
    services:
      - xvfb
    before_script:
      - Rscript -e 'install.packages("devtools", type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/map@development", dependencies = TRUE)'
      - Rscript -e 'devtools::install_github("PredictiveEcology/pemisc@development", dependencies = TRUE)'
    before_install:
      - Rscript -e 'install.packages(c("ggplot2", "quickPlot", "reproducible", "rgdal", "rgeos", "SpaDES.core"), type = "source")'
    r_github_packages:
      - jimhester/lintr
      - r-lib/covr
    after_failure:
      - cat ./LandR.Rcheck/tests/test-all.Rout
    after_success:
      - travis_wait 15 Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
      - Rscript -e 'lintr::lint_package()'
  - os: linux
    dist: xenial
    r: devel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - hunspell-en-ca
          - libgdal1-dev
          - libgeos-dev
          - libglpk-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
    services:
      - xvfb
    before_script:
      - Rscript -e 'install.packages("devtools", type = "source")'
      - Rscript -e 'devtools::install_github("PredictiveEcology/map@development", dependencies = TRUE)'
      - Rscript -e 'devtools::install_github("PredictiveEcology/pemisc@development", dependencies = TRUE)'
    before_install:
      - Rscript -e 'install.packages(c("ggplot2", "quickPlot", "reproducible", "rgdal", "rgeos", "SpaDES.core"), type = "source")'
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - glpk
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    env:
      - GLPK=true
    before_install:
      - Rscript -e 'install.packages(c("digest", "igraph", "rgdal", "rgeos"), type = "source")'
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    env:
      - GLPK=false
    before_script:
      - Rscript -e 'install.packages(c("digest", "igraph", "rgdal", "rgeos"), type = "source")'
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
