sudo: required
language: r
cache: packages
cran: https://cran.rstudio.com/
env:
  global:
    - CRAN_REPO=https://cran.rstudio.com
matrix:
  include:
  - os: linux
    dist: trusty
    r: 3.3
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 # give xvfb some time to start
    r_packages:
      - rgdal
      - rgeos
  - os: linux
    dist: trusty
    r: 3.4
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 # give xvfb some time to start
    r_packages:
      - rgdal
      - rgeos
  - os: linux
    dist: trusty
    r: oldrel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 # give xvfb some time to start
    r_packages:
      - rgdal
      - rgeos
  - os: linux
    dist: trusty
    r: release
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 # give xvfb some time to start
    r_packages:
      - covr
      - devtools
    r_github_packages:
      - jimhester/lintr
    after_success:
      - Rscript -e 'covr::coveralls(type = "all", quiet = FALSE)'
      - Rscript -e 'lintr::lint_package()'
    r_packages:
      - rgdal
      - rgeos
  - os: linux
    dist: trusty
    r: devel
    addons:
      apt:
        sources:
          - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
        packages:
          - libgdal-dev
          - libgdal1-dev
          - libgeos-dev
          - libnlopt-dev
          - libproj-dev
          - libudunits2-dev
          - gdal-bin
    before_script:
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      - sleep 3 # give xvfb some time to start
    r_packages:
      - devtools
      - rgdal
      - rgeos
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - glpk
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    env:
      - GLPK=true
    before_install:
      - Rscript -e 'install.packages(c("digest", "igraph", "rgdal", "rgeos"), type = "source")'
  - os: osx
    osx_image: xcode9.4
    addons:
      homebrew:
        packages:
        - libgit2
        - llvm
        - udunits
        update: true
    latex: false
    r_build_args: "--no-build-vignettes"
    r_check_args: "--as-cran --ignore-vignettes --no-examples"
    env:
      - GLPK=false
    before_script:
      - Rscript -e "install.packages(c('rgdal', 'rgeos'), type = 'source')"
r_build_args: " "
r_check_args: "--as-cran"
warnings_are_errors: true
notifications:
  email:
    on_success: change
    on_failure: change
