on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

name: test-coverage

jobs:
  test-coverage:
    if: "!contains(github.event.commits[0].message, '[skip-ci]')"
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: PredictiveEcology/actions/install-spatial-deps@main

      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://PredictiveEcology.r-universe.dev/'
          use-public-rspm: false

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::sf
            any::XML
            BioSIM=?ignore
            fastshp=?ignore
            NLMR=?ignore
            PredictiveEcology/quickPlot@development
            PredictiveEcology/reproducible@development
            PredictiveEcology/Require@development
            PredictiveEcology/SpaDES.core@development
            PredictiveEcology/SpaDES.tools@development

      - name: Install additional package dependencies
        run: |
          pak::pkg_install("remotes")
          remotes::install_github("RNCan/BioSimClient_R")
          remotes::install_github("ropensci/NLMR")
          remotes::install_github("s-u/fastshp")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
